### ISSUE TITLE
Fails on Intel Braswell BSP

### ISSUE THREAD

**Issue by JeffMarqMetrix** [ms-iot/iot-adk-addonkit#163]
Trying to use Intel's latest BSP release for Braswell processors is giving me issues.

Here's where I obtained the BSP:
https://www.intel.com/content/www/us/en/embedded/products/braswell/software-and-drivers.html

BSP Download URL:
https://edc.intel.com/Link.aspx?id=14935

Using the 1709 Addon Kit downloaded from the master branch in GitHub results in the following errors:

[JetwaySBC1_Test.log]:
```
Creating JetwaySBC1 Test Image
Build Start Time : 13:47:45.22
Building Packages with product specific contents with version 10.0.0.0
 Processing Registry.Version.wm.xml
 Processing Custom.Cmd.wm.xml
 Processing JetwaySBC1
 Processing Provisioning.Auto.wm.xml
Running FeatureMerger for OEM packages
  Exporting OEMFM files
  Processing OEMFMFileList.xml
Running FeatureMerger for BSWx64
  Exporting BSWx64 FM files
  Processing BSWx64FMFileList.xml
Creating Image...
Microsoft (C) imageapp 10.0.10011.16384

ImageApp!ConfigureServicingStackLogging: Failed initializing WdsCore.dll.
ImageApp: Setting CPU Type to 'amd64'.
info: Imaging: Reading the OEM Input XML file...
info: FeatureAPI: Successfully validated the OEM Input XML: C:\IoT-ADK-AddonKit\Source-x64\Products\JetwaySBC1\TestOEMInput.xml
info: Imaging: Reading the FM XML file 'C:\IoT-ADK-AddonKit\Source-x64\BSP\BSWx64\Packages\BSWx64FM.xml'...
info: FeatureAPI: Successfully validated the Feature Manifest XML: C:\IoT-ADK-AddonKit\Source-x64\BSP\BSWx64\Packages\BSWx64FM.xml
fatal error : Imaging!ProcessCompDBPackages: FIP information in FM 'BSWx64FM.xml' packages for the following Features are incorrect: 
fatal error : 	Error : BASE
fatal error : 	Error : OEM_BSW64_DRIVERS
fatal error : 	Error : OEMDEVICEPLATFORM_BSWX64_DEVICE
fatal error : 	Error : DEVICELAYOUT_BSWX64_SOC
info: Imaging: See Flash.cbs.log and Flash.csi.log for details.
info: Imaging: Performance Results:
info: 	Total Run Time:	00:00:01.1726105
info: 	Storage Stack Time:	00:00:00
info: 	CompDB Total Time:	00:00:00.8819263
ImageApp: Error log can be found at 'C:\IoT-ADK-AddonKit\Build\amd64\JetwaySBC1\Test\Flash.ImageApp.log'.
Failed to add CBS file logger.
"CreateImage JetwaySBC1 Test" failed with error 1
```

I was then told that the version 3.2 of the AddonKit is what the current Intel BSP works against. And that there are changes checked into the develop branch that should address the issue.

For the version 3.2, buildpkg all doesn't even complete without errors. Here are the errors for buildpkg:

[Appx.IoTCoreDefaultApp.pkg.log]:
```
Creating Provisioning Package using C:\iot-adk-addonkit-3.2\Source-x64\Packages\Appx.IoTCoreDefaultApp\customizations.xml

Microsoft (C) Windows Imaging and Configuration Designer

ICD.exe : ERROR: The following errors were detected in customizations:
ICD.exe : ERROR: Settings were not found in the store file.
ICD.exe : ERROR: Parse error (0x80070490): 'ApplicationManagement' is not a valid child node for /
ICD.exe : ERROR: C:\Users\jscherrer\Documents\Windows Imaging and Configuration Designer (WICD)\Common\ICDCommon_20171106-131905-279_6636.log
"provpkg C:\iot-adk-addonkit-3.2\Source-x64\Packages\Appx.IoTCoreDefaultApp\customizations.xml" failed with error 100
```

[Appx.IoTOnboardingTask.prov.log]:
```
Creating Provisioning Package using C:\iot-adk-addonkit-3.2\Source-x64\Packages\Appx.IoTOnboardingTask\customizations.xml

Microsoft (C) Windows Imaging and Configuration Designer

ICD.exe : ERROR: The following errors were detected in customizations:
ICD.exe : ERROR: Settings were not found in the store file.
ICD.exe : ERROR: Parse error (0x80070490): 'ApplicationManagement' is not a valid child node for /
ICD.exe : ERROR: C:\Users\jscherrer\Documents\Windows Imaging and Configuration Designer (WICD)\Common\ICDCommon_20171106-131905-561_12932.log
"provpkg C:\iot-adk-addonkit-3.2\Source-x64\Packages\Appx.IoTOnboardingTask\customizations.xml" failed with error 100
```

[SampleAProv.prov.log]:
```
Creating Provisioning Package using C:\iot-adk-addonkit-3.2\Source-x64\Products\SampleA\prov\customizations.xml

Microsoft (C) Windows Imaging and Configuration Designer

ICD.exe : ERROR: The following errors were detected in customizations:
ICD.exe : ERROR: Settings were not found in the store file.
ICD.exe : ERROR: Parse error (0x80070490): 'ApplicationManagement' is not a valid child node for /
ICD.exe : ERROR: C:\Users\jscherrer\Documents\Windows Imaging and Configuration Designer (WICD)\Common\ICDCommon_20171106-131905-842_4328.log
"provpkg C:\iot-adk-addonkit-3.2\Source-x64\Products\SampleA\prov\customizations.xml" failed with error 100
```

[Provisioning.Auto.pkg.log]:
```
Creating Provisioning.Auto.pkg.xml Package with version 10.0.0.0 for SampleA
Microsoft (C) PkgGen 10.0.10011.16384

Running SPkgGen.exe C:\iot-adk-addonkit-3.2\Common\Packages\Provisioning.Auto\Provisioning.Auto.pkg.xml /config:"C:\Program Files (x86)\Windows Kits\10\Tools\bin\i386\pkggen.cfg.xml" /output:C:\iot-adk-addonkit-3.2\Build\amd64\pkgs /build:fre /cpu:amd64 /variables:_RELEASEDIR=C:\iot-adk-addonkit-3.2\Common\Packages\Provisioning.Auto\;PROD=SampleA;PRJDIR=C:\iot-adk-addonkit-3.2\Source-x64;COMDIR=C:\iot-adk-addonkit-3.2\Common;BSPVER=10.0.0.0;BSPARCH=amd64;OEMNAME=Intel;BUILDTIME=171106-1319;BUILD_OS_VERSION=10.0.0.0 /toolPaths:%RazzleToolPath%\x86 /nohives /version:10.0.0.0 /spkgsout:C:\Users\jscherrer\AppData\Local\Temp\tmpF6D7.tmp 
--Stack Trace--
   at Microsoft.CompPlat.PkgBldr.Base.Run.RunSPkgGen(List`1 pkgGenArgs, Boolean inWindows, IDeploymentLogger logger, PkgBldrCmd pkgBldrArgs, List`1 spkgList)
   at Microsoft.CompPlat.PkgBldr.Program.PkgToCab(Config config, List`1 spkgGenArgs, Boolean testSignOnly)
   at Microsoft.CompPlat.PkgBldr.Program.Main(String[] args)
--End Stack Trace--
Package creation failed with error -1
```

[Appx.IoTCoreDefaultApp.pkg.log]:
```
Creating Appx.IoTCoreDefaultApp.pkg.xml Package with version 10.0.0.0 for SampleA
 Creating C:\iot-adk-addonkit-3.2\Source-x64\Packages\Appx.IoTCoreDefaultApp\Appx.IoTCoreDefaultApp.ppkg...
Creating Provisioning Package using customizations.xml

Microsoft (C) Windows Imaging and Configuration Designer

ICD.exe : ERROR: The following errors were detected in customizations:
ICD.exe : ERROR: Settings were not found in the store file.
ICD.exe : ERROR: Parse error (0x80070490): 'ApplicationManagement' is not a valid child node for /
ICD.exe : ERROR: C:\Users\jscherrer\Documents\Windows Imaging and Configuration Designer (WICD)\Common\ICDCommon_20171106-131920-953_264.log
"provpkg customizations.xml" failed with error 100
Microsoft (C) PkgGen 10.0.10011.16384

Running SPkgGen.exe C:\iot-adk-addonkit-3.2\Source-x64\Packages\Appx.IoTCoreDefaultApp\Appx.IoTCoreDefaultApp.pkg.xml /config:"C:\Program Files (x86)\Windows Kits\10\Tools\bin\i386\pkggen.cfg.xml" /output:C:\iot-adk-addonkit-3.2\Build\amd64\pkgs /build:fre /cpu:amd64 /variables:_RELEASEDIR=C:\iot-adk-addonkit-3.2\Source-x64\Packages\Appx.IoTCoreDefaultApp\;PROD=SampleA;PRJDIR=C:\iot-adk-addonkit-3.2\Source-x64;COMDIR=C:\iot-adk-addonkit-3.2\Common;BSPVER=10.0.0.0;BSPARCH=amd64;OEMNAME=Intel;BUILDTIME=171106-1319;BUILD_OS_VERSION=10.0.0.0 /toolPaths:%RazzleToolPath%\x86 /nohives /version:10.0.0.0 /spkgsout:C:\Users\jscherrer\AppData\Local\Temp\tmp1888.tmp 
--Stack Trace--
   at Microsoft.CompPlat.PkgBldr.Base.Run.RunSPkgGen(List`1 pkgGenArgs, Boolean inWindows, IDeploymentLogger logger, PkgBldrCmd pkgBldrArgs, List`1 spkgList)
   at Microsoft.CompPlat.PkgBldr.Program.PkgToCab(Config config, List`1 spkgGenArgs, Boolean testSignOnly)
   at Microsoft.CompPlat.PkgBldr.Program.Main(String[] args)
--End Stack Trace--
Package creation failed with error -1
```

[Appx.IoTOnboardingTask.pkg.log]:
```
Creating Appx.IoTOnboardingTask.pkg.xml Package with version 10.0.0.0 for SampleA
 Creating C:\iot-adk-addonkit-3.2\Source-x64\Packages\Appx.IoTOnboardingTask\Appx.IoTOnboardingTask.ppkg...
Creating Provisioning Package using customizations.xml

Microsoft (C) Windows Imaging and Configuration Designer

ICD.exe : ERROR: The following errors were detected in customizations:
ICD.exe : ERROR: Settings were not found in the store file.
ICD.exe : ERROR: Parse error (0x80070490): 'ApplicationManagement' is not a valid child node for /
ICD.exe : ERROR: C:\Users\jscherrer\Documents\Windows Imaging and Configuration Designer (WICD)\Common\ICDCommon_20171106-131921-594_11284.log
"provpkg customizations.xml" failed with error 100
Microsoft (C) PkgGen 10.0.10011.16384

Running SPkgGen.exe C:\iot-adk-addonkit-3.2\Source-x64\Packages\Appx.IoTOnboardingTask\Appx.IoTOnboardingTask.pkg.xml /config:"C:\Program Files (x86)\Windows Kits\10\Tools\bin\i386\pkggen.cfg.xml" /output:C:\iot-adk-addonkit-3.2\Build\amd64\pkgs /build:fre /cpu:amd64 /variables:_RELEASEDIR=C:\iot-adk-addonkit-3.2\Source-x64\Packages\Appx.IoTOnboardingTask\;PROD=SampleA;PRJDIR=C:\iot-adk-addonkit-3.2\Source-x64;COMDIR=C:\iot-adk-addonkit-3.2\Common;BSPVER=10.0.0.0;BSPARCH=amd64;OEMNAME=Intel;BUILDTIME=171106-1319;BUILD_OS_VERSION=10.0.0.0 /toolPaths:%RazzleToolPath%\x86 /nohives /version:10.0.0.0 /spkgsout:C:\Users\jscherrer\AppData\Local\Temp\tmp1AEA.tmp 
--Stack Trace--
   at Microsoft.CompPlat.PkgBldr.Base.Run.RunSPkgGen(List`1 pkgGenArgs, Boolean inWindows, IDeploymentLogger logger, PkgBldrCmd pkgBldrArgs, List`1 spkgList)
   at Microsoft.CompPlat.PkgBldr.Program.PkgToCab(Config config, List`1 spkgGenArgs, Boolean testSignOnly)
   at Microsoft.CompPlat.PkgBldr.Program.Main(String[] args)
--End Stack Trace--
Package creation failed with error -1
```

[buildfm_oem.log]:
```
info: Trying to load file 'C:\iot-adk-addonkit-3.2\Build\amd64\InputFMs\OEMFMFileList.xml' as a FM file list ...
fatal error : Error: Missing package: C:\iot-adk-addonkit-3.2\Build\amd64\pkgs\Intel.Provisioning.Auto.cab
fatal error : Error: Missing package: C:\iot-adk-addonkit-3.2\Build\amd64\pkgs\Intel.Provisioning.Auto.cab
fatal error : Error: Missing package: C:\iot-adk-addonkit-3.2\Build\amd64\pkgs\Intel.Appx.IoTCoreDefaultApp.cab
fatal error : Error: Missing package: C:\iot-adk-addonkit-3.2\Build\amd64\pkgs\Intel.Appx.IoTOnboardingTask.cab
```

[buildfm_bsp_CustomMBMx64.log]:
```
info: Trying to load file 'C:\iot-adk-addonkit-3.2\Build\amd64\InputFMs\CustomMBMx64FMFileList.xml' as a FM file list ...
fatal error : Error: Missing package: C:\iot-adk-addonkit-3.2\Build\amd64\pkgs\Intel.MBMx64.GPIO.cab
fatal error : Error: Missing package: C:\iot-adk-addonkit-3.2\Build\amd64\pkgs\Intel.MBMx64.UART.cab
fatal error : Error: Missing package: C:\iot-adk-addonkit-3.2\Build\amd64\pkgs\Intel.MBMx64.I2C.cab
fatal error : Error: Missing package: C:\iot-adk-addonkit-3.2\Build\amd64\pkgs\Intel.MBMx64.SPI.cab
fatal error : Error: Missing package: C:\iot-adk-addonkit-3.2\Build\amd64\pkgs\Intel.MBMx64.GRFX.cab
```

[buildfm_bsp_MBMx64.log]:
```
info: Trying to load file 'C:\iot-adk-addonkit-3.2\Build\amd64\InputFMs\MBMx64FMFileList.xml' as a FM file list ...
fatal error : Error: Missing package: C:\iot-adk-addonkit-3.2\Build\amd64\pkgs\Intel.MBMx64.GPIO.cab
fatal error : Error: Missing package: C:\iot-adk-addonkit-3.2\Build\amd64\pkgs\Intel.MBMx64.UART.cab
fatal error : Error: Missing package: C:\iot-adk-addonkit-3.2\Build\amd64\pkgs\Intel.MBMx64.I2C.cab
fatal error : Error: Missing package: C:\iot-adk-addonkit-3.2\Build\amd64\pkgs\Intel.MBMx64.SPI.cab
fatal error : Error: Missing package: C:\iot-adk-addonkit-3.2\Build\amd64\pkgs\Intel.MBMx64.GRFX.cab
```

Since many of the errors didn't seem directly related to my device, I went ahead with buildimage anyways, and the following errors occurred:

[JetwaySBC1_Test.log]:
```
Creating JetwaySBC1 Test Image
Build Start Time : 13:30:13.69
Building Packages with product specific contents
 Processing Registry.Version.pkg.xml
 Processing Custom.Cmd.pkg.xml
Creating Provisioning Package using C:\iot-adk-addonkit-3.2\Source-x64\Products\JetwaySBC1\prov\customizations.xml

Microsoft (C) Windows Imaging and Configuration Designer

ICD.exe : ERROR: The following errors were detected in customizations:
ICD.exe : ERROR: Settings were not found in the store file.
ICD.exe : ERROR: Parse error (0x80070490): 'ApplicationManagement' is not a valid child node for /
ICD.exe : ERROR: C:\Users\jscherrer\Documents\Windows Imaging and Configuration Designer (WICD)\Common\ICDCommon_20171106-133015-674_3500.log
"provpkg C:\iot-adk-addonkit-3.2\Source-x64\Products\JetwaySBC1\prov\customizations.xml" failed with error 100
 Processing Provisioning.Auto.pkg.xml
[91mError : Failed to create package. See C:\iot-adk-addonkit-3.2\Build\amd64\pkgs\logs\Provisioning.Auto.pkg.log[0m
Creating Image...
Microsoft (C) imageapp 10.0.10011.16384

ImageApp!ConfigureServicingStackLogging: Failed initializing WdsCore.dll.
ImageApp: Setting CPU Type to 'amd64'.
info: Imaging: Reading the OEM Input XML file...
info: FeatureAPI: Successfully validated the OEM Input XML: C:\iot-adk-addonkit-3.2\Source-x64\Products\JetwaySBC1\TestOEMInput.xml
info: Imaging: Reading the FM XML file 'C:\iot-adk-addonkit-3.2\Source-x64\BSP\BSWx64\Packages\BSWx64FM.xml'...
info: FeatureAPI: Successfully validated the Feature Manifest XML: C:\iot-adk-addonkit-3.2\Source-x64\BSP\BSWx64\Packages\BSWx64FM.xml
fatal error : Imaging!ProcessCompDBPackages: FIP information in FM 'BSWx64FM.xml' packages for the following Features are incorrect: 
fatal error : 	Error : BASE
fatal error : 	Error : OEM_BSW64_DRIVERS
fatal error : 	Error : OEMDEVICEPLATFORM_BSWX64_DEVICE
fatal error : 	Error : DEVICELAYOUT_BSWX64_SOC
info: Imaging: See Flash.cbs.log and Flash.csi.log for details.
info: Imaging: Performance Results:
info: 	Total Run Time:	00:00:01.1277237
info: 	Storage Stack Time:	00:00:00
info: 	CompDB Total Time:	00:00:00.8457621
ImageApp: Error log can be found at 'C:\iot-adk-addonkit-3.2\Build\amd64\JetwaySBC1\Test\Flash.ImageApp.log'.
Failed to add CBS file logger.
"CreateImage JetwaySBC1 Test" failed with error 1
```

So I went ahead and tried to target the latest develop branch. The results were more like what I saw from the 1709 release. The buildpkg all completes fine. But buildimage fails with the following errors:

[JetwaySBC1_Test.log]:
```
Creating JetwaySBC1 Test Image
Build Start Time : 13:39:26.14
Building Packages with product specific contents with version 10.0.0.0
 Processing Registry.Version.wm.xml
 Processing Custom.Cmd.wm.xml
 Processing JetwaySBC1
 Processing Provisioning.Auto.wm.xml
Running FeatureMerger for OEM packages
  Exporting OEMFM files
  Processing OEMFMFileList.xml
Running FeatureMerger for BSWx64
  Exporting BSWx64 FM files
  Processing BSWx64FMFileList.xml
Creating Image...
Microsoft (C) imageapp 10.0.10011.16384

ImageApp!ConfigureServicingStackLogging: Failed initializing WdsCore.dll.
ImageApp: Setting CPU Type to 'amd64'.
info: Imaging: Reading the OEM Input XML file...
info: FeatureAPI: Successfully validated the OEM Input XML: C:\Users\jscherrer\source\repos\iot-adk-addonkit\Source-x64\Products\JetwaySBC1\TestOEMInput.xml
info: Imaging: Reading the FM XML file 'C:\Users\jscherrer\source\repos\iot-adk-addonkit\Source-x64\BSP\BSWx64\Packages\BSWx64FM.xml'...
info: FeatureAPI: Successfully validated the Feature Manifest XML: C:\Users\jscherrer\source\repos\iot-adk-addonkit\Source-x64\BSP\BSWx64\Packages\BSWx64FM.xml
fatal error : Imaging!ProcessCompDBPackages: FIP information in FM 'BSWx64FM.xml' packages for the following Features are incorrect: 
fatal error : 	Error : BASE
fatal error : 	Error : OEM_BSW64_DRIVERS
fatal error : 	Error : OEMDEVICEPLATFORM_BSWX64_DEVICE
fatal error : 	Error : DEVICELAYOUT_BSWX64_SOC
info: Imaging: See Flash.cbs.log and Flash.csi.log for details.
info: Imaging: Performance Results:
info: 	Total Run Time:	00:00:01.1442189
info: 	Storage Stack Time:	00:00:00
info: 	CompDB Total Time:	00:00:00.8467266
ImageApp: Error log can be found at 'C:\Users\jscherrer\source\repos\iot-adk-addonkit\Build\amd64\JetwaySBC1\Test\Flash.ImageApp.log'.
Failed to add CBS file logger.
"CreateImage JetwaySBC1 Test" failed with error 1
```

**Comment by parameshbabu** [comment]
Hi @JeffMarqMetrix 
For using the 15063_v3 you also need to use the corresponding ADK tools. Looks like you are using the latest ADK tools. I suggest you look at the outstanding PR changes and give it a try, if you want to stay with the latest tools and master branch. This is pending validation currently.

**Comment by JeffMarqMetrix** [comment]
Hi @parameshbabu 
I did try the latest PR changes (I think). The very last log output was the result I got from that attempt.

I'm pretty sure I tested the right bits. I fetched everything from the "develop" branch. I will try again today, and let you know.

**Comment by parameshbabu** [comment]
My bad, I should have mentioned that you need to run the script that is part for the PR , tools\bsptools\BSWx64\convert.cmd, which does the patching of the files to make it work with latest tools.

**Comment by JeffMarqMetrix** [comment]
Hey @parameshbabu 
That could be the issue. But I'm not seeing that file in the develop branch. The only folder I see in bsptools is QCDB410C (I'm guessing for the DragonBoard). And there is no convert.cmd in there.

**Comment by parameshbabu** [comment]
https://github.com/ms-iot/iot-adk-addonkit/pull/161/commits/62466ffd21bb6457a13ffff977413060ee1f63ed 
this is not integrated yet.

**Comment by JeffMarqMetrix** [comment]
It builds the image successfully.

But I'm now having an issue when the OS starts. The screen goes blank. I think it's just because I didn't specify a default app to run, since I've been moving these XML files around quite a bit.

Will try to see if that's the issue and report back.

Thanks for your help!

**Comment by JeffMarqMetrix** [comment]
Everything works!!! Thanks again!
